### ISSUE TITLE
[FEATURE] 회원가입 화면 & 기능 수정

### ISSUE THREAD

**Issue by Cho-SangHyun** [SWmaestro-14th-somsatang/wooyoungsoo-FE#24]
## Description
회원가입 화면 및 기능 수정하기

## Todo
- [x] 회원가입 화면 UI 수정
- [x] 회원가입 기능 수정
    - [x] 프로필 이미지 첨부 기능 추가
    - [x] 약관 동의 버튼 추가

## ETC
다음 디자인을 참고한다.
![회원가입](https://github.com/SWmaestro-14th-somsatang/petdori-FE/assets/65762283/9a90bda8-8978-43ee-ad20-64c6ac0ae4d6)
