### ISSUE TITLE
[FEATURE] 강아지 등록화면 UI, 기능 수정

### ISSUE THREAD

**Issue by Cho-SangHyun** [SWmaestro-14th-somsatang/wooyoungsoo-FE#30]
## Description
강아지 등록화면 UI, 기능 수정

## Todo
- [x] 사진 업로드 기능 추가
- [x] 나이가 아닌 생년월일 입력하도록 변경
- [x] 견종목록 백엔드에서 받아오는 기능 추가
- [x] UI 변경

## ETC
UI는 다음 디자인을 참고

<p align="center"><img src="https://github.com/SWmaestro-14th-somsatang/petdori-FE/assets/65762283/347eba30-e426-45fe-b9b6-add4f49008b0" height="600px"></p>
